version: '3.1'
services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
      MARIADB_USER: "chef"
      MARIADB_PASSWORD: "devuseonly"
      MARIADB_DATABASE: "cookbook"
    ports:
      - "3306:3306"
    volumes:
      - "../data:/var/lib/mysql"
